name: Display-File
on:
  pull_request:
    branches: ["dev/prod"]
jobs:
  display-file-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat README.md
  display-file-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: type README.md
    
